language: python
python:
- '3.6'
before_install:
  - sudo apt-get install xvfb
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
install:
- pip install -r requirements.txt
- python mysite/manage.py collectstatic --noinput
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin
  - sudo chmod a+x /usr/bin/chromedriver

script: python mysite/manage.py test sum



