language: python
python:
- '3.6'

sudo: false

before_install:
  - apt-get install xvfb

install:
- pip install -r requirements.txt
- python mysite/manage.py collectstatic --noinput
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.13/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/bin
  - chmod a+x /usr/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


script: python mysite/manage.py test sum



