language: python
python:
- '3.6'
before_install:
  - sudo apt-get install xvfb
install:
- pip install -r requirements.txt
- python mysite/manage.py collectstatic --noinput
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sudo chmod a+x /usr/local/bin/chromedriver

script: python mysite/manage.py test sum
cache: pip



