language: python
python:
- '3.6'

before_install:
  - sudo apt-get install xvfb
  - sudo apt-get -f install
  - sudo apt-get install libfontconfig1 libstdc++6 lsb-base


addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

install:
- pip install -r requirements.txt
- python mysite/manage.py collectstatic --noinput
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.13/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin
  - sudo chmod a+x /usr/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script: python mysite/manage.py test sum



