language: python
python:
- '3.6'
before_install:
  - sudo apt-get install xvfb
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
install:
- pip install -r requirements.txt
- python mysite/manage.py collectstatic --noinput
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin
  - sudo chmod a+x /usr/bin/chromedriver

script: python mysite/manage.py test sum



